# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
permalink: /:year-:month-:day-:title/
#relative_permalinks: true
excerpt_separator: "<!--more-->"

plugins:          [jekyll-paginate]

# Setup
title:            Alexei Kojenov
tagline:          'Alexei Kojenov'
description:      'Random thoughts on random things'
url:              http://kojenov.com
baseurl:          /

author:
  name:           'Alexei Kojenov'
  url:            https://twitter.com/kojenov

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
